### PR TITLE
remove need for hcb stats page for deploy

### LINKED ISSUE #1454: [HCB] Allow site to build without HCB's stats endpoint
We've temporarily disabled HCB's stats endpoint which is causing site builds to fail. We should make it so that this site repo does not depend on external APIs to build.

Related: https://github.com/hackclub/site/issues/716

### PR DESCRIPTION
**Pull request by rluodev**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/fiscal-sponsorship/first**](https://site-875j9k86j.hackclub.dev/fiscal-sponsorship/first) | [**/**](https://site-875j9k86j.hackclub.dev/) |
|:-:|:-:|
|<a href="https://site-875j9k86j.hackclub.dev/fiscal-sponsorship/first">Screenshot of /fiscal-sponsorship/first</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/calSWxWNfsfjnOwdlqDxU6DH6Go2ejWMLOYjCRrAk2bS9dZrg7JJ1yQpN7FaJdTTSDNGaaMAz8_NGhlF8-VOmQ.png">(view full size)</a> |<a href="https://site-875j9k86j.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ufeaUPVyC11Vw6BcRTd4CNoKSXgsA7bP2wNp9xeOJLNRjb3WWn779RFEg0yUxzgucJQrnl09otmtrT9zmflH0g.png">(view full size)</a> |







Commit ebb22163ab7e59fe2bf11241d7ce9065fc4fca86 (https://site-875j9k86j.hackclub.dev).

File: components/fiscal-sponsorship/first/stats.js [hunk 1]
```diff
@@ -103,11 +105,20 @@ const Stats = ({ stats }) => {
...
-  return {
-    props: {
-      stats
+  try {
+    const stats = await res.json()
+    return {
+      props: {
+        stats
+      },
+      revalidate: 10
```
Comment (garyhtou) [inline components/fiscal-sponsorship/first/stats.js:114]: good call on the revalidate for get static props.

instead of every 10 seconds. maybe we do once an hour? or even once a day? these numbers don't change that quickly.

File: pages/index.js [hunk 2]
```diff
@@ -1221,17 +1221,20 @@ export async function getStaticProps() {
...
-    })} raised`
-  )
+    bankData.push(
+      `💰 ${raised.toLocaleString('en-US', {
+        style: 'currency',
+        currency: 'USD'
+      })} raised`
+    )
+  } catch {
+    bankData.push('error')
```
Comment (garyhtou) [inline pages/index.js:1236]: What if we pushed nothing? then in the card, we could replace:

```js
data[0] === 'error' ? 'The coolest money thing' : data[0]
```

with

```js
data[0] || 'The coolest money thing'
```

**Comment by garyhtou** [comment]
lmk once you have the lint errors fixed

**Comment by rluodev** [comment]
@garyhtou the lint errors aren't related to my changes, they've been an issue on every pr in this repo
